const fs = require('fs');
let html = fs.readFileSync('index.html', 'utf8');

html = html.replace(/<label>[^<]*<input id="eatKcal100"[^>]*><\/label><label>[^<]*<input id="eatProt100"[^>]*><\/label>/, '<label>Всего ккал в этой порции<input id="eatKcalTotal" type="number" min="0" value="430"></label><label>Всего белка в этой порции, г<input id="eatProtTotal" type="number" min="0" step="0.1" value="37"></label>');
html = html.replace(/<label>[^<]*<input id="eatGrams" type="number" min="0" value="250"><\/label>/, '<label>Общий вес порции, г или мл<input id="eatGrams" type="number" min="0" value="450"></label>');
html = html.replace(/if\(raw==='custom'\)\{name=val\('eatName'\)\|\|[^;]+;kcal=num\('eatKcal100'\)\*g\/100;protein=num\('eatProt100'\)\*g\/100\}/, "if(raw==='custom'){name=val('eatName')||'Свое блюдо';kcal=num('eatKcalTotal');protein=num('eatProtTotal')}");
html = html.replace('<h3>Что съедено сегодня</h3><div class="diary-grid">', '<h3>Быстрая запись еды</h3><p class="muted">Если итог уже известен: например 450 г, 430 ккал и 37 г белка, внесите эти числа напрямую. Пересчет на 100 г не нужен.</p><div class="diary-grid">');

const training = `function renderTraining(p){let gentle=p.markers.includes('joints')||p.markers.includes('pressure')||p.markers.includes('cortisol'),base=['Силовая дома: ноги и корпус','Верх тела с рюкзаком','Ходьба 45 минут','Круг без прыжков','Ягодицы и бедра','Растяжка и спина','Интервальная ходьба','Корпус и осанка','Легкая зарядка утром','Ступеньки или подъемы','Домашняя силовая 20 минут','Тренировка с бутылками','Мобилизация тазобедренных','Спокойное кардио дома','Руки и плечи','Ноги без выпадов','Пресс без скручиваний','Восстановительная прогулка','Силовой круг 3 раунда','Ходьба после еды','Тренировка при стрессе','Низ тела без прыжков','Спина и лопатки','Баланс и стопы','Быстрый комплекс 12 минут','Растяжка перед сном','Круг на все тело','Легкий день после алкоголя','Силовая с паузами','Кардио на месте','Техника приседа','Плечи и грудь','Ягодичный мост и корпус','Длинная прогулка','Мягкая тренировка при давлении','Свободный день с шагами','Плавный старт','Антиотечная ходьба','Домашний комплекс 35 минут','Вечерняя растяжка'],list=base.map((title,i)=>({title:'День '+(i+1)+': '+title,text:gentle?gentleText(i):regularText(i)}));$('training').innerHTML='<div class="advice ok"><b>Тренировки:</b> добавлено 40 разных вариантов. При кортизоле, давлении или суставах приложение выбирает мягкий формат без прыжков.</div><div class="workout-list">'+list.map(x=>'<div class="workout"><img src="'+img.work+'" alt="Тренировка дома"><div class="body"><h4>'+x.title+'</h4><p>'+x.text+'</p></div></div>').join('')+'</div>'}function regularText(i){let a=['присед к стулу 3 x 12, ягодичный мост 3 x 15, планка 3 x 25 секунд','отжимания от стола 3 x 10, тяга рюкзака 3 x 12, руки с бутылками 3 x 12','быстрая ходьба 35-50 минут, в конце 5 минут растяжки','4 круга: шаги 60 секунд, присед 12 раз, тяга 12 раз, мост 15 раз','выпад назад 3 x 10, мост 3 x 15, отведение ноги 3 x 12'];return a[i%a.length]}function gentleText(i){let a=['ходьба 30-45 минут и мягкая растяжка 6 минут','присед к стулу 2 x 10, тяга полотенца 2 x 12, мост 2 x 12','10 минут ходьбы после 2 приемов пищи, вечером дыхание 5 минут','шаги на месте 5 минут, подъем на носки 2 x 15, спина у стены 2 x 10','восстановительный день: прогулка и сон без силовой нагрузки'];return a[i%a.length]}function toggleBeat(){}function renderAdvice(p,s)`;
html = html.replace(/function renderTraining\(p\)\{[\s\S]*?function renderAdvice\(p,s\)/, training);

const script = html.match(/<script>([\s\S]*)<\/script>/);
if (!script) throw new Error('script not found');
new Function(script[1]);
fs.writeFileSync('index.html', html, 'utf8');
